# Clear existing data
puts "Clearing database..."
Bid.destroy_all
StackAsset.destroy_all
Transaction.destroy_all
Wallet.destroy_all

puts "Seeding Wallet..."
# Seed wallet with initial funds
Wallet.create!(balance: 156700.0)

puts "Seeding Transactions..."
# Historical transactions
Transaction.create!(
  amount: 300000.0,
  transaction_type: "deposit",
  description: "Initial Venture Capital Funding",
  timestamp: 10.days.ago
)
Transaction.create!(
  amount: -95000.0,
  transaction_type: "purchase",
  description: "Purchased 'Web3 Auction Titan' at Hackathon Auction",
  timestamp: 5.days.ago
)
Transaction.create!(
  amount: -50000.0,
  transaction_type: "purchase",
  description: "Purchased 'The Bootstrap Legacy' portfolio asset",
  timestamp: 4.days.ago
)
Transaction.create!(
  amount: 1250.0,
  transaction_type: "dividend",
  description: "Weekly yield payout from 'Web3 Auction Titan'",
  timestamp: 2.days.ago
)
Transaction.create!(
  amount: 450.0,
  transaction_type: "dividend",
  description: "Weekly yield payout from 'The Bootstrap Legacy'",
  timestamp: 2.days.ago
)

puts "Seeding Stack Assets..."
# Active auction items
stack1 = StackAsset.create!(
  name: "The Hackathon Holy Grail",
  technologies: "Vue.js, Tailwind CSS, Ruby on Rails, SQLite",
  description: "The ultra-rapid, lightweight prototype stack purchased by our team at the auction. Extremely fast development cycles, seamless local SQLite storage, and beautiful frontend widgets.",
  valuation: 75000.0,
  monthly_roi: 4.8,
  risk_level: "Low",
  status: "active_auction",
  current_bid: 75000.0,
  highest_bidder: "Simulated Rival B",
  owner_name: nil,
  image_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=400&q=80",
  earnings: 0.0
)

# Seed historical bids on this active auction item
Bid.create!(stack_asset: stack1, bidder_name: "Simulated Rival A", amount: 70000.0, timestamp: 3.hours.ago)
Bid.create!(stack_asset: stack1, bidder_name: "Simulated Rival B", amount: 75000.0, timestamp: 1.hour.ago)

stack2 = StackAsset.create!(
  name: "Vue-Rails FinTech Elite",
  technologies: "Vue 3, Tailwind v4, Ruby on Rails 8, Postgres",
  description: "A high-frequency wealth management and financial analytics dashboard stack. Features extreme visual aesthetics, heavy math modules, and custom visual charts.",
  valuation: 120000.0,
  monthly_roi: 6.2,
  risk_level: "High",
  status: "active_auction",
  current_bid: 110000.0,
  highest_bidder: "Venture Whale 1",
  owner_name: nil,
  image_url: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=400&q=80",
  earnings: 0.0
)
Bid.create!(stack_asset: stack2, bidder_name: "Seed Investor", amount: 100000.0, timestamp: 5.hours.ago)
Bid.create!(stack_asset: stack2, bidder_name: "Venture Whale 1", amount: 110000.0, timestamp: 2.hours.ago)

StackAsset.create!(
  name: "SQLite Agile Ledger",
  technologies: "Ruby on Rails, SQLite, Bootstrap, Stimulus",
  description: "An ultra-lean personal ledger and auditing stack. Focuses on rapid local-first storage and high database write performance without complex server setups.",
  valuation: 35000.0,
  monthly_roi: 2.8,
  risk_level: "Low",
  status: "active_auction",
  current_bid: 35000.0,
  highest_bidder: "Bootstrap Bob",
  owner_name: nil,
  image_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=400&q=80",
  earnings: 0.0
)

StackAsset.create!(
  name: "AI Analytics Brain",
  technologies: "Python, PyTorch, React, SQLite",
  description: "A premium data engineering and neural network processing stack. Generates huge returns by running offline background workers, but carries significant infrastructure risk.",
  valuation: 180000.0,
  monthly_roi: 8.5,
  risk_level: "High",
  status: "active_auction",
  current_bid: 165000.0,
  highest_bidder: "Nvidia Fanboy",
  owner_name: nil,
  image_url: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=400&q=80",
  earnings: 0.0
)

# Owned assets
StackAsset.create!(
  name: "Web3 Auction Titan",
  technologies: "Vue.js, Tailwind CSS, Solidity, IPFS",
  description: "Decentralized auction houses for smart contract assets. Sleek, secure, and has a steady weekly return generated by smart contract royalties.",
  valuation: 95000.0,
  monthly_roi: 5.4,
  risk_level: "Medium",
  status: "owned",
  current_bid: 0.0,
  highest_bidder: nil,
  owner_name: "You",
  image_url: "https://images.unsplash.com/photo-1639322537228-f710d846310a?auto=format&fit=crop&w=400&q=80",
  earnings: 1250.0
)

StackAsset.create!(
  name: "The Bootstrap Legacy",
  technologies: "jQuery, PHP, MySQL",
  description: "An old-school highly profitable e-commerce funnel. Not shiny, but generates steady, low-risk dividends every day with close to zero maintenance overhead.",
  valuation: 50000.0,
  monthly_roi: 3.1,
  risk_level: "Low",
  status: "owned",
  current_bid: 0.0,
  highest_bidder: nil,
  owner_name: "You",
  image_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=400&q=80",
  earnings: 450.0
)

puts "Seeding Completed!"
